### ISSUE TITLE
Add a small tub under paraformaldehyde to segregate solids from liquids in case of a spill

### ISSUE THREAD

**Issue by zaneveld** [zaneveld/lab_safety#15]

**Comment by tanyabrown9** [comment]
I placed the paraformaldehyde that is ours in its own container. The large jug of formaldehyde is still in the hood because I can't find room for it in the cabinet.

**Comment by zaneveld** [comment]
Nice! Thanks! Closing. We'll have EH&S pick up the paraformaldehyde.
