### ISSUE TITLE
Find spill kit

### ISSUE THREAD

**Issue by zaneveld** [zaneveld/lab_safety#19]

**Comment by tanyabrown9** [comment]
I can't find the one in the lab (I see one in every other room). It looks like the kit needs to ordered through VWR using Ariba. https://www.ehs.washington.edu/system/files/resources/Focus_Sheet-Ordering_a_Spill_Kit.pdf

**Comment by zaneveld** [comment]
New kit ordered by Christy Cherrier 6/15/23

**Comment by zaneveld** [comment]
Fixed - now by the door to the teaching lab
