### ISSUE TITLE
Remove acetone & acetone waste from fume hood

### ISSUE THREAD

**Issue by zaneveld** [zaneveld/lab_safety#21]
The acetone needs to go in the flammable cabinet, along with the paraformaldehyde

**Comment by tanyabrown9** [comment]
I think the reason these are out is that there is no more room in the cabinet! I am unsure how to solve this.

**Comment by zaneveld** [comment]
OK, let's then contact EH&S and dispose of them since we're not doing FISH right now.

**Comment by tanyabrown9** [comment]
I cleaned up all the glassware in the hood. There are several racks of PCR tubes and some waste that looks like it belongs to Dr. Madzima (the waste is labeled with her name and the tubes are right behind it). I left those.

**Comment by zaneveld** [comment]
Thanks! Resolved
